### ISSUE TITLE
latest config.yaml incorrectly set to 1.2.10 

### ISSUE THREAD

**Issue by Lytanshade** [plemeri/transparent-background#65]
Hi there, 

Very useful app, thanks for this!

A fresh install of transparent-background has a `config.yaml` with the old download urls.  So it 404 errors when trying to download the models.

```
 base:
  url: "https://github.com/plemeri/transparent-background/releases/download/1.2.10/ckpt_base.pth"
  md5: "d692e3dd5fa1b9658949d452bebf1cda"
  ckpt_name: "ckpt_base.pth"
  http_proxy: NULL
  base_size: [1024, 1024]
...
```

my prior install had the config url correctly set to 1.2.12
